# Generated by Django 3.2.6 on 2021-08-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='Address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='pincode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobileno',
            field=models.IntegerField(blank=True),
        ),
    ]
