# Generated by Django 3.2.6 on 2021-08-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_subcategory_subimage'),
        ('UserRecord', '0005_auto_20210821_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='myorder',
            field=models.ManyToManyField(blank=True, null=True, to='Products.Product'),
        ),
    ]
