# Generated by Django 3.2.6 on 2021-08-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserRecord', '0006_alter_userprofile_myorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='myorder',
        ),
    ]
