# Generated by Django 3.2.6 on 2021-08-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserRecord', '0008_useraddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
