# Generated by Django 3.2.6 on 2021-08-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=('ss', 4), unique=True),
            preserve_default=False,
        ),
    ]
