# Generated by Django 3.2.6 on 2021-08-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20210819_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimg',
            name='image',
            field=models.FileField(blank=True, upload_to='ProductImage/'),
        ),
    ]
