# Generated by Django 3.2.6 on 2021-08-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=('ss',), upload_to='Category/'),
            preserve_default=False,
        ),
    ]
