# Generated by Django 3.2.6 on 2021-08-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='subimage',
            field=models.ImageField(default=('ss',), upload_to='Category/subcategory/'),
            preserve_default=False,
        ),
    ]
