# Generated by Django 3.2.6 on 2021-08-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0016_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cart',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
