# Generated by Django 3.2.6 on 2021-08-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0017_auto_20210823_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='cart',
            field=models.BooleanField(default=True),
        ),
    ]
