# Generated by Django 3.2.6 on 2021-08-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0018_alter_orderitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='isordered',
            field=models.BooleanField(default=False),
        ),
    ]
